config/routes.rb
Epetition::Application.routes.draw do
  resources :users
  resources :petitions
  root :to => 'petitions#index'

end

app/models/petition.rb
class Petition < ActiveRecord::Base
  attr_accessible :description, :name, :pdf_link
  has_many :user_petitions
  has_many :users, :through => :user_petitions
end

app/controllers/petitions_controller.rb
require 'net/https'
require 'uri'
require 'json'

class PetitionsController < ApplicationController
  # GET /petitions
  # GET /petitions.json
  def index
    @petitions = Petition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @petitions, callback: params[:callback] }
    end
  end

  # GET /petitions/1
  # GET /petitions/1.json
  def show
    @petition = Petition.find(params[:id])

    puts "PDF Link url = "
    @petition.pdf_link =  view_document(create_envelope(get_template))
    
    puts @petition.pdf_link

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/new
  # GET /petitions/new.json
  def new
    @petition = Petition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/1/edit
  def edit
    @petition = Petition.find(params[:id])
  end

  # POST /petitions
  # POST /petitions.json
  def create
    @petition = Petition.new(params[:petition])

    respond_to do |format|
      if @petition.save
        format.html { redirect_to @petition, notice: 'Petition was successfully created.' }
        format.json { render json: @petition, status: :created, location: @petition }
      else
        format.html { render action: "new" }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /petitions/1
  # PUT /petitions/1.json
  def update
    @petition = Petition.find(params[:id])

    respond_to do |format|
      if @petition.update_attributes(params[:petition])
        format.html { redirect_to @petition, notice: 'Petition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petitions/1
  # DELETE /petitions/1.json
  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy

    respond_to do |format|
      format.html { redirect_to petitions_url }
      format.json { head :no_content }
    end
  end

  def get_template
    docusign_authentication_headers = {
            "X-DocuSign-Authentication" => "" \
              "<DocuSignCredentials>" \
                "<Username>rhuff.9999@gmail.com</Username>" \
                "<Password>Deskpro0docusign</Password>" \
                "<IntegratorKey>NAXX-b2095226-449e-4c21-9f8b-5c3ca4287c07</IntegratorKey>" \
              "</DocuSignCredentials>"
    }

    accept_headers = {"Accept" => "application/json"}
    #puts docusign_authentication_headers
    #puts accept_headers
    #puts docusign_authentication_headers.merge(accept_headers)
    headers = docusign_authentication_headers.merge(accept_headers)

    uri = URI.parse("https://demo.docusign.net/restapi/v2/accounts/203548/templates")
    request = Net::HTTP::Get.new(uri.request_uri, headers)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = http.request(request).body 
    #puts response

    hashed_response = JSON.parse(response)
    templates = hashed_response['envelopeTemplates']
    templateId = templates[0]['templateId']

    puts "****************"
    templateId
  end

def create_envelope(templateId)
  puts "~~~~~~~~~~~~ "
  puts templateId

    docusign_authentication_headers = {
            "X-DocuSign-Authentication" => "" \
              "<DocuSignCredentials>" \
                "<Username>rhuff.9999@gmail.com</Username>" \
                "<Password>Deskpro0docusign</Password>" \
                "<IntegratorKey>NAXX-b2095226-449e-4c21-9f8b-5c3ca4287c07</IntegratorKey>" \
              "</DocuSignCredentials>"
    }

    content_type_header = {"content-type" => "application/json"}
    accept_headers = {"Accept" => "application/json"}
    #puts docusign_authentication_headers
    #puts accept_headers
    #puts docusign_authentication_headers.merge(accept_headers)
    headers = docusign_authentication_headers.merge(accept_headers).merge(content_type_header)

    blurb = "Blurb"
    subject = "Subject"
    email = "james.hwang.usc@gmail.com"
    name = "James Hwang"
    roleName = "RoleOne"
    clientUserId = "1"
    status = "sent"


    post_body = "{
        \"emailBlurb\"   : \"" + blurb + "\",
        \"emailSubject\" : \"" + subject + "\",
        \"templateId\"    : \"" + templateId + "\",
        \"customFields\"  : {
          \"textCustomFields\" : [{
            \"name\" : \"lastName\",
            \"show\" : \"true\",
            \"required\" : \"true\",
            \"value\" : \"Smith\"
          }]
        },
        \"templateRoles\"   : [ {
          \"email\" : \"" + email + "\",
          \"name\" :  \"" + name + "\",
          \"roleName\" :  \"" + roleName + "\",
          \"clientUserId\" :  \"" + clientUserId + "\"}],
        \"status\" : \"" + status + "\"
      }"

    uri = URI.parse("https://demo.docusign.net/restapi/v2/accounts/203548/envelopes")
    request = Net::HTTP::Post.new(uri.request_uri, headers)
    request.body = post_body
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = http.request(request).body 
    puts response

    hashed_response = JSON.parse(response)
    envelope_id = hashed_response['envelopeId']

    envelope_id
  end

def view_document(envelopeId)
  puts "~~~~~~~~~~~~ "
  puts envelopeId

    docusign_authentication_headers = {
            "X-DocuSign-Authentication" => "" \
              "<DocuSignCredentials>" \
                "<Username>rhuff.9999@gmail.com</Username>" \
                "<Password>Deskpro0docusign</Password>" \
                "<IntegratorKey>NAXX-b2095226-449e-4c21-9f8b-5c3ca4287c07</IntegratorKey>" \
              "</DocuSignCredentials>"
    }

    content_type_header = {"content-type" => "application/json"}
    accept_headers = {"Accept" => "application/json"}
    #puts docusign_authentication_headers
    #puts accept_headers
    #puts docusign_authentication_headers.merge(accept_headers)
    headers = docusign_authentication_headers.merge(accept_headers).merge(content_type_header)

    blurb = "Blurb"
    subject = "Subject"
    email = "james.hwang.usc@gmail.com"
    name = "Name"
    roleName = "RoleOne"
    clientUserId = "1"
    status = "sent"

    post_body = "{
        \"authenticationMethod\"   : \"None\",
        \"email\" : \"james.hwang.usc@gmail.com\",
        \"returnUrl\" : \"http://easypetition.herokuapp.com/close.html\",
        \"userName\" : \"James Hwang\",
        \"clientUserId\" : \"1\"
      }"

    uri = URI.parse("https://demo.docusign.net/restapi/v2/accounts/203548/envelopes/" + envelopeId + "/views/recipient")
    request = Net::HTTP::Post.new(uri.request_uri, headers)
    request.body = post_body
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = http.request(request).body 

    hashed_response = JSON.parse(response)
    document_url = hashed_response['url']

    document_url

#    templates = hashed_response[0]['envelopeId']

  end
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/views/petitions/_form.html.erb
<%= form_for @petition, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pdf_link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pdf_link, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                petitions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/petitions/edit.html.erb
<%- model_class = Petition -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/petitions/index.html.erb
<%- model_class = Petition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:pdf_link) %></th>
      
    </tr>
  </thead>
  <tbody>
    <% @petitions.each do |petition| %>
      <tr>
        <td><%= link_to petition.name, petition_path(petition) %></td>
        <td><%= link_to petition.description[0,250], petition_path(petition) %></td>
        <td><%= petition.pdf_link %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/petitions/new.html.erb
<%- model_class = Petition -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/petitions/show.html.erb
<div id="container">
  <%- model_class = Petition -%>
  <div class="page-header">
    <h1><%= image_tag("https://s3-us-west-2.amazonaws.com/pastepaste/images/logo.png") %></h1>
  </div>

  <dl class="dl-horizontal">
    <dd style="margin-left: 35px;font-weight: bold; font-size: 22px;"><%= @petition.name %></dd>
    
    <dd style="margin-left: 35px;"><%= @petition.description %></dd>
  </dl>

  <iframe src="<%= @petition.pdf_link %>" style="width:900px; height: 700px;" frameborder="0"></iframe>
</div>